package generator

import (
	"fmt"
	"strconv"

	"github.com/artem-kuznetsov-intellectsoft/openapi2go/openapi"
)

// walkPaths pre-generates the types referenced by every operation's
// requestBody and 4xx/5xx responses, in path/method/status-code order, so
// they render in that order rather than the alphabetical order the
// components.schemas pass would otherwise produce. Anything not reached
// this way (2xx responses, schemas unused by any operation) still gets
// generated by the components.schemas pass that follows.
func (g *generator) walkPaths(paths openapi.Paths) {
	for _, path := range sortedKeys(paths) {
		item := paths[path]
		if item == nil {
			continue
		}

		for _, mo := range []struct {
			httpMethod string
			op         *openapi.Operation
		}{
			{"http.MethodGet", item.Get},
			{"http.MethodPut", item.Put},
			{"http.MethodPost", item.Post},
			{"http.MethodDelete", item.Delete},
			{"http.MethodOptions", item.Options},
			{"http.MethodHead", item.Head},
			{"http.MethodPatch", item.Patch},
			{"http.MethodTrace", item.Trace},
		} {
			if mo.op != nil {
				g.walkOperation(path, mo.httpMethod, mo.op, item.Parameters)
			}
		}
	}
}

// walkOperation registers op's Params/requestBody/response types (as before)
// and additionally records a clientMethodDef from the exact type names those
// steps resolve, so client.go generation can never drift from what was
// actually declared — see registerClientMethod.
func (g *generator) walkOperation(
	path, httpMethod string,
	op *openapi.Operation,
	pathParams []*openapi.RefOr[*openapi.Parameter],
) {
	paramsType := g.registerParamsStruct(op, pathParams)
	requestType := g.registerOperationRequestBody(op)
	responseType, clientErrors := g.walkOperationResponses(op)

	g.registerClientMethod(&clientMethodDef{
		name:         toPascalCase(op.OperationID),
		operationID:  op.OperationID,
		httpMethod:   httpMethod,
		path:         path,
		paramsType:   paramsType,
		requestType:  requestType,
		responseType: responseType,
		errors:       clientErrors,
	})
}

// registerOperationRequestBody generates op's requestBody schema, exactly
// like registerInlineResponse does for a response, and returns its Go type
// name ("" if op has no requestBody or content).
func (g *generator) registerOperationRequestBody(op *openapi.Operation) string {
	if op.RequestBody == nil || op.RequestBody.Value == nil {
		return ""
	}

	schema := firstJSONSchema(op.RequestBody.Value.Content)
	if schema == nil {
		return ""
	}

	requestType := g.resolveRefOrType("requestBody", schema).typ
	g.flushPendingInline()

	return requestType
}

// minErrorStatus/maxErrorStatus and minSuccessStatus/maxSuccessStatus bound
// the 4xx/5xx and 2xx status-code ranges walkOperationResponses classifies
// each response by.
const (
	minErrorStatus   = 400
	maxErrorStatus   = 599
	minSuccessStatus = 200
	maxSuccessStatus = 299
)

// walkOperationResponses registers every response of op (error and
// non-error alike, via registerErrorResponse/registerInlineResponse) and
// reports the pieces a client method needs: the Go type name of the first
// 2xx response with a schema (in status-code order), and every 4xx/5xx case
// for the method's response switch.
func (g *generator) walkOperationResponses(op *openapi.Operation) (string, []clientErrorDef) {
	responseType := ""
	var clientErrors []clientErrorDef

	for _, code := range sortedKeys(op.Responses) {
		resp := op.Responses[code]
		if resp == nil || resp.Value == nil {
			continue
		}

		errDef, successType := g.registerOperationResponse(code, resp.Value)
		if errDef != nil {
			clientErrors = append(clientErrors, *errDef)
			continue
		}

		if responseType == "" && successType != "" {
			responseType = successType
		}
	}

	return responseType, clientErrors
}

// registerOperationResponse registers one response code's schema (via
// registerErrorResponse for 4xx/5xx, registerInlineResponse otherwise) and
// classifies it for walkOperationResponses: a 4xx/5xx code returns a non-nil
// errDef; a 2xx code with a schema returns its Go type name as successType.
func (g *generator) registerOperationResponse(code string, resp *openapi.Response) (*clientErrorDef, string) {
	status, statusErr := strconv.Atoi(code)

	if statusErr == nil && status >= minErrorStatus && status <= maxErrorStatus {
		schema := firstJSONSchema(resp.Content)
		typeName := g.registerErrorResponse(code, schema)
		g.flushPendingInline()

		return &clientErrorDef{code: code, typ: typeName, hasSchema: schema != nil}, ""
	}

	typeName := g.registerInlineResponse(code, resp)
	g.flushPendingInline()

	if statusErr == nil && status >= minSuccessStatus && status <= maxSuccessStatus {
		return nil, typeName
	}

	return nil, ""
}

// registerInlineResponse generates a type for a non-error (1xx/2xx/3xx, or
// "default") response's schema when it's inline, mirroring requestBody
// handling. A schema that's a $ref (or
// allOf-wrapped nullable $ref) into components.schemas is left untouched
// here: it has no inline content of its own to generate, so it's picked up
// by the later alphabetical components.schemas pass instead, preserving the
// existing declaration order for named 2xx/3xx/default schemas. Returns the
// response's Go type name in both cases (even though the $ref case doesn't
// generate it here), or "" if resp has no schema at all.
func (g *generator) registerInlineResponse(code string, resp *openapi.Response) string {
	schema := firstJSONSchema(resp.Content)
	if schema == nil {
		return ""
	}

	if name, _, ok := unwrapRef(schema); ok {
		return name
	}

	typeName := g.resolveRefOrType("Response"+toPascalCase(code), schema).typ

	return typeName
}

// registerParamsStruct generates a "<PascalCase(operationId)>Params" struct
// for op's path/query/header/cookie parameters, merging pathParams (declared
// on the enclosing PathItem) with op.Parameters (operation-level parameters
// override a path-level one of the same name). Skipped when op has no
// operationId (there would be no name to give the struct) or no parameters
// at all. Returns the struct's name, or "" when skipped.
func (g *generator) registerParamsStruct(
	op *openapi.Operation,
	pathParams []*openapi.RefOr[*openapi.Parameter],
) string {
	if op.OperationID == "" {
		return ""
	}

	byName := map[string]*openapi.Parameter{}
	for _, ref := range pathParams {
		if p := g.resolveParameter(ref); p != nil {
			byName[p.Name] = p
		}
	}
	for _, ref := range op.Parameters {
		if p := g.resolveParameter(ref); p != nil {
			byName[p.Name] = p
		}
	}

	if len(byName) == 0 {
		return ""
	}

	name := toPascalCase(op.OperationID) + "Params"
	if g.markGenerated(name) {
		return name
	}

	fields := make([]fieldDef, 0, len(byName))
	for _, paramName := range sortedKeys(byName) {
		fields = append(fields, g.buildParamField(byName[paramName]))
	}

	g.addStruct(&structDef{
		name:    name,
		comment: fmt.Sprintf("%s is generated for operationId %s.", name, op.OperationID),
		fields:  fields,
	})

	return name
}

// resolveParameter dereferences a parameter that may be a direct $ref into
// components.parameters.
func (g *generator) resolveParameter(ref *openapi.RefOr[*openapi.Parameter]) *openapi.Parameter {
	if ref == nil {
		return nil
	}

	if ref.Ref != "" {
		return g.parameters[lastPathSegment(ref.Ref)]
	}

	return ref.Value
}

// buildParamField resolves the Go field for a single operation parameter. A
// path parameter is always treated as required per the OpenAPI spec,
// regardless of its declared "required" value. Unlike schema fields,
// parameter fields carry no json tag (they're bound from path/query/header
// values, not JSON) and optionality is expressed purely with a pointer,
// since there's no ",omitempty" tag to do that job instead.
func (g *generator) buildParamField(param *openapi.Parameter) fieldDef {
	typ := goAny
	if param.Schema != nil {
		typ = g.resolveRefOrType(param.Name, param.Schema).typ
	}

	required := param.Required || param.In == "path"
	if !required && isPointerable(typ) {
		typ = "*" + typ
	}

	return fieldDef{name: toPascalCase(param.Name), typ: typ, paramName: param.Name, in: param.In}
}

// errorTODOBody is the Error() method body for every 4xx/5xx response type:
// the generator has no way to know what the correct output is (which field
// of an arbitrary schema holds the error message, or what a content-less
// response should report), so it always stubs the body out for the
// developer to fill in by hand.
const errorTODOBody = `panic("TODO: define the output")`

// registerErrorResponse generates the type for a 4xx/5xx response's schema
// (the first JSON media type's schema of its content, or nil if it has none)
// and gives it an `Error() string` method: a schema-backed response resolves
// to its named struct, while a nil schema synthesizes an empty
// "Response<code>" struct. Both get the same errorTODOBody. Returns the
// error type's Go name.
func (g *generator) registerErrorResponse(code string, schema *openapi.RefOr[*openapi.Schema]) string {
	if schema == nil {
		return g.registerNoContentErrorResponse(code)
	}

	typeName := g.resolveRefOrType("Response"+code, schema).typ
	if def, ok := g.structIndex[typeName]; ok && def.errorBody == "" {
		def.errorBody = errorTODOBody
	}

	return typeName
}

func (g *generator) registerNoContentErrorResponse(code string) string {
	name := "Response" + code
	if g.markGenerated(name) {
		return name
	}

	g.addStruct(&structDef{name: name, errorBody: errorTODOBody})

	return name
}

// firstJSONSchema returns the schema of the first media type in content,
// in sorted key order, or nil if content has none.
func firstJSONSchema(content map[string]*openapi.MediaType) *openapi.RefOr[*openapi.Schema] {
	for _, key := range sortedKeys(content) {
		if mt := content[key]; mt != nil && mt.Schema != nil {
			return mt.Schema
		}
	}

	return nil
}
