package generator

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/artem-kuznetsov-intellectsoft/openapi2go/openapi"
)

// walkPaths pre-generates the types referenced by every operation's
// requestBody and 4xx/5xx responses, in path/method/status-code order, so
// they render in that order rather than the alphabetical order the
// components.schemas pass would otherwise produce. Anything not reached
// this way (2xx responses, schemas unused by any operation) still gets
// generated by the components.schemas pass that follows.
func (g *generator) walkPaths(paths openapi.Paths) {
	for _, path := range sortedKeys(paths) {
		item := paths[path]
		if item == nil {
			continue
		}

		for _, mo := range []struct {
			httpMethod string
			op         *openapi.Operation
		}{
			{"http.MethodGet", item.Get},
			{"http.MethodPut", item.Put},
			{"http.MethodPost", item.Post},
			{"http.MethodDelete", item.Delete},
			{"http.MethodOptions", item.Options},
			{"http.MethodHead", item.Head},
			{"http.MethodPatch", item.Patch},
			{"http.MethodTrace", item.Trace},
		} {
			if mo.op != nil {
				g.walkOperation(path, mo.httpMethod, mo.op, item.Parameters)
			}
		}
	}
}

// walkOperation registers op's Params/requestBody/response types (as before)
// and additionally records a clientMethodDef from the exact type names those
// steps resolve, so client.go generation can never drift from what was
// actually declared — see registerClientMethod.
func (g *generator) walkOperation(
	path, httpMethod string,
	op *openapi.Operation,
	pathParams []*openapi.RefOr[*openapi.Parameter],
) {
	paramsType := g.registerParamsStruct(op, pathParams)
	requestType := g.registerOperationRequestBody(op)
	responses := g.walkOperationResponses(op)

	g.registerClientMethod(&clientMethodDef{
		name:             toPascalCase(op.OperationID),
		operationID:      op.OperationID,
		httpMethod:       httpMethod,
		path:             path,
		paramsType:       paramsType,
		requestType:      requestType,
		responseType:     responses.successType,
		errors:           responses.errors,
		defaultErrorType: responses.defaultType,
	})
}

// registerOperationRequestBody generates op's requestBody schema under the
// name "<PascalCase(operationId)>Request" (registerRequestWrapper), so each
// operation gets its own named request type instead of every operation
// sharing the raw schema type. Returns "" if op has no requestBody, no
// content, or no operationId to name the type after.
func (g *generator) registerOperationRequestBody(op *openapi.Operation) string {
	if op.RequestBody == nil || op.RequestBody.Value == nil || op.OperationID == "" {
		return ""
	}

	schema := firstJSONSchema(op.RequestBody.Value.Content)
	if schema == nil {
		return ""
	}

	return g.registerRequestWrapper(op.OperationID, schema)
}

// registerRequestWrapper generates the Go type for a requestBody schema
// under the name "<PascalCase(operationId)>Request", exactly mirroring the
// $ref/inline distinction registerInlineResponse makes for a response: a
// schema that's a $ref (or allOf-wrapped nullable $ref) into
// components.schemas names a type worth keeping distinct from the
// operation-specific wrapper, so the wrapper struct embeds it (its position
// in g.structs is reserved before resolving the embedded type, so the
// wrapper renders ahead of it rather than after). Any other, inline schema
// — an object literal, array, oneOf, or multi-member allOf composition, none
// of which have a name of their own — has nothing worth keeping separate,
// so its fields are generated directly under the wrapper's name instead.
func (g *generator) registerRequestWrapper(operationID string, schema *openapi.RefOr[*openapi.Schema]) string {
	name := toPascalCase(operationID) + "Request"

	refName, _, isRef := unwrapRef(schema)
	if !isRef {
		g.resolveRefOrType(name, schema)
		g.flushPendingInline()

		return name
	}

	if g.markGenerated(name) {
		return name
	}

	def := &structDef{name: name}
	g.addStruct(def)

	def.fields = []fieldDef{{typ: g.resolveNamedType(refName), embedded: true}}

	return name
}

// minErrorStatus/maxErrorStatus and minSuccessStatus/maxSuccessStatus bound
// the 4xx/5xx and 2xx status-code ranges walkOperationResponses classifies
// each response by.
const (
	minErrorStatus   = 400
	maxErrorStatus   = 599
	minSuccessStatus = 200
	maxSuccessStatus = 299
)

// defaultResponseCode is the OpenAPI key for "every status not listed
// explicitly", which the client uses as its non-2xx fallback.
const defaultResponseCode = "default"

// operationResponses is what a client method needs from op's responses.
type operationResponses struct {
	// successType is the Go type of the first 2xx response with a schema, in
	// status-code order.
	successType string
	// errors is every 4xx/5xx case for the method's response switch.
	errors []clientErrorDef
	// defaultType is the Go type of the "default" response, or "".
	defaultType string
}

// walkOperationResponses registers every response of op (error and non-error
// alike, via registerErrorResponse/registerInlineResponse) and reports the
// pieces a client method needs.
func (g *generator) walkOperationResponses(op *openapi.Operation) operationResponses {
	var out operationResponses

	for _, code := range sortedKeys(op.Responses) {
		resp := op.Responses[code]
		if resp == nil || resp.Value == nil {
			continue
		}

		if code == defaultResponseCode {
			out.defaultType = g.registerDefaultResponse(resp.Value)

			continue
		}

		errDef, successType := g.registerOperationResponse(op.OperationID, code, resp.Value)
		if errDef != nil {
			out.errors = append(out.errors, *errDef)

			continue
		}

		if out.successType == "" && successType != "" {
			out.successType = successType
		}
	}

	return out
}

// registerDefaultResponse generates the type for a "default" response and
// gives it an Error() method, since that is the role the client puts it in:
// the payload for any status no explicit case claimed. Returns "" when the
// response declares no schema, leaving the plain envelope as the fallback.
func (g *generator) registerDefaultResponse(resp *openapi.Response) string {
	schema := firstJSONSchema(resp.Content)
	if schema == nil {
		return ""
	}

	typeName := g.registerErrorResponse("Default", schema)
	g.flushPendingInline()

	return typeName
}

// registerOperationResponse registers one response code's schema (via
// registerErrorResponse for 4xx/5xx, registerInlineResponse otherwise) and
// classifies it for walkOperationResponses: a 4xx/5xx code returns a non-nil
// errDef; a 2xx code with a schema returns its Go type name as successType.
func (g *generator) registerOperationResponse(operationID, code string, resp *openapi.Response) (*clientErrorDef, string) {
	status, statusErr := strconv.Atoi(code)

	if statusErr == nil && status >= minErrorStatus && status <= maxErrorStatus {
		schema := firstJSONSchema(resp.Content)
		typeName := g.registerErrorResponse(code, schema)
		g.flushPendingInline()

		return &clientErrorDef{code: code, typ: typeName, hasSchema: schema != nil}, ""
	}

	typeName := g.registerInlineResponse(operationID, code, resp)
	g.flushPendingInline()

	if statusErr == nil && status >= minSuccessStatus && status <= maxSuccessStatus {
		return nil, typeName
	}

	return nil, ""
}

// registerInlineResponse generates a type for a non-error (1xx/2xx/3xx, or
// "default") response's schema when it's inline, mirroring requestBody
// handling (registerRequestWrapper). A schema that's a $ref (or
// allOf-wrapped nullable $ref) into components.schemas is left untouched
// here: it has no inline content of its own to generate, so it's picked up
// by the later alphabetical components.schemas pass instead, preserving the
// existing declaration order for named 2xx/3xx/default schemas. Any other,
// inline schema has no name of its own worth keeping, so its fields are
// generated directly under "<PascalCase(operationId)>Response<code>"
// instead of a name shared across every operation's same-numbered response.
// Returns the response's Go type name in both cases (even though the $ref
// case doesn't generate it here), or "" if resp has no schema at all.
func (g *generator) registerInlineResponse(operationID, code string, resp *openapi.Response) string {
	schema := firstJSONSchema(resp.Content)
	if schema == nil {
		return ""
	}

	if name, _, ok := unwrapRef(schema); ok {
		return name
	}

	name := toPascalCase(operationID) + "Response" + toPascalCase(code)
	typeName := g.resolveRefOrType(name, schema).typ

	return typeName
}

// registerParamsStruct generates a "<PascalCase(operationId)>Params" struct
// for op's path/query/header/cookie parameters, merging pathParams (declared
// on the enclosing PathItem) with op.Parameters (operation-level parameters
// override a path-level one of the same name). Skipped when op has no
// operationId (there would be no name to give the struct) or no parameters
// at all. Returns the struct's name, or "" when skipped.
func (g *generator) registerParamsStruct(
	op *openapi.Operation,
	pathParams []*openapi.RefOr[*openapi.Parameter],
) string {
	if op.OperationID == "" {
		return ""
	}

	byName := map[string]*openapi.Parameter{}
	for _, ref := range pathParams {
		if p := g.resolveParameter(ref); p != nil {
			byName[p.Name] = p
		}
	}
	for _, ref := range op.Parameters {
		if p := g.resolveParameter(ref); p != nil {
			byName[p.Name] = p
		}
	}

	if len(byName) == 0 {
		return ""
	}

	name := toPascalCase(op.OperationID) + "Params"
	if g.markGenerated(name) {
		return name
	}

	fields := make([]fieldDef, 0, len(byName))
	for _, paramName := range sortedKeys(byName) {
		fields = append(fields, g.buildParamField(byName[paramName]))
	}

	g.addStruct(&structDef{
		name:    name,
		comment: fmt.Sprintf("%s is generated for operationId %s.", name, op.OperationID),
		fields:  fields,
	})

	return name
}

// resolveParameter dereferences a parameter that may be a direct $ref into
// components.parameters.
func (g *generator) resolveParameter(ref *openapi.RefOr[*openapi.Parameter]) *openapi.Parameter {
	if ref == nil {
		return nil
	}

	if ref.Ref != "" {
		return g.parameters[lastPathSegment(ref.Ref)]
	}

	return ref.Value
}

// buildParamField resolves the Go field for a single operation parameter. A
// path parameter is always treated as required per the OpenAPI spec,
// regardless of its declared "required" value. Unlike schema fields,
// parameter fields carry no json tag (they're bound from path/query/header
// values, not JSON) and optionality is expressed purely with a pointer,
// since there's no ",omitempty" tag to do that job instead.
func (g *generator) buildParamField(param *openapi.Parameter) fieldDef {
	typ := goAny
	if param.Schema != nil {
		typ = g.resolveRefOrType(param.Name, param.Schema).typ
	}

	required := param.Required || param.In == "path"
	if !required && isPointerable(typ) {
		typ = "*" + typ
	}

	return fieldDef{name: toPascalCase(param.Name), typ: typ, paramName: param.Name, in: param.In}
}

// messageFieldNames are the JSON property names a schema is assumed to use
// for a human-readable error message, in the order they are preferred.
//
//nolint:gochecknoglobals // a fixed lookup table, not mutable state
var messageFieldNames = []string{"message", "error", "error_description", "detail", "title", "reason", "description"}

// registerErrorResponse generates the type for a 4xx/5xx response's schema
// (the first JSON media type's schema of its content) and gives it an
// `Error() string` method, returning the type's Go name.
//
// A response with no content gets no type at all: the client's expectSuccess
// already turns any non-2xx into an *APIError carrying the status, headers,
// and body, which is strictly more than an empty marker struct could report —
// and a marker named after the status code alone would be shared by every
// operation returning that status, so it could never discriminate between
// them anyway. Returns "" in that case.
func (g *generator) registerErrorResponse(code string, schema *openapi.RefOr[*openapi.Schema]) string {
	if schema == nil {
		return ""
	}

	typeName := g.resolveRefOrType("Response"+code, schema).typ
	if def, ok := g.structIndex[typeName]; ok && def.errorBody == "" {
		def.errorBody = errorBodyFor(def)
	}

	return typeName
}

// errorBodyFor builds the Error() method body for an error response type.
// When the schema has a string field that reads like a message, that field is
// the message; otherwise the fields are dumped.
func errorBodyFor(def *structDef) string {
	if field, ok := messageField(def.fields); ok {
		return fmt.Sprintf("if r.%s != \"\" {\nreturn r.%s\n}\n\nreturn %q", field, field, def.name)
	}

	if len(def.fields) == 0 {
		return fmt.Sprintf("return %q", def.name)
	}

	// The local defined type is load-bearing: %+v on a value that implements
	// error would re-enter Error forever, which go vet rejects outright
	// ("causes recursive (T).Error method call"). plain has an identical
	// layout and no methods.
	return fmt.Sprintf("type plain %s\n\nreturn fmt.Sprintf(%q, plain(r))", def.name, def.name+"%+v")
}

// goString is the Go type name a message field must have.
const goString = "string"

// messageField returns the name of the first string field whose JSON property
// name reads like a human-readable error message.
func messageField(fields []fieldDef) (string, bool) {
	for _, want := range messageFieldNames {
		for _, f := range fields {
			if f.embedded || f.typ != goString {
				continue
			}

			if strings.EqualFold(jsonFieldName(f.jsonTag), want) {
				return f.name, true
			}
		}
	}

	return "", false
}

// jsonFieldName returns the property name part of a json struct tag value,
// dropping any ",omitempty"-style options.
func jsonFieldName(tag string) string {
	name, _, _ := strings.Cut(tag, ",")

	return name
}

// firstJSONSchema returns the schema of the first media type in content,
// in sorted key order, or nil if content has none.
func firstJSONSchema(content map[string]*openapi.MediaType) *openapi.RefOr[*openapi.Schema] {
	for _, key := range sortedKeys(content) {
		if mt := content[key]; mt != nil && mt.Schema != nil {
			return mt.Schema
		}
	}

	return nil
}
