package generator

import (
	"fmt"
	"strings"
)

// generatedFileHeader marks every emitted file as generated. Beyond the
// convention itself, the "Code generated ... DO NOT EDIT." form is what makes
// golangci-lint (and a consumer's linter) skip these files by default.
const generatedFileHeader = "// Code generated by openapi2go. DO NOT EDIT.\n\n"

func (g *generator) render(pkgName string) string {
	var b strings.Builder

	b.WriteString(generatedFileHeader)
	fmt.Fprintf(&b, "package %s\n\n", pkgName)

	if g.usesFmt() {
		b.WriteString("import \"fmt\"\n\n")
	}

	for _, e := range g.enums {
		renderEnum(&b, e)
	}

	for _, s := range g.structs {
		renderStruct(&b, s)
	}

	return b.String()
}

// usesFmt reports whether any rendered Error method needs the fmt import.
func (g *generator) usesFmt() bool {
	for _, s := range g.structs {
		if s.errorBody != "" && strings.Contains(s.errorBody, "fmt.") {
			return true
		}
	}

	return false
}

func renderEnum(b *strings.Builder, e *enumDef) {
	if sentence := describeSentence(e.description); sentence != "" {
		fmt.Fprintf(b, "// %s represents the %s.\n", e.name, sentence)
	}

	fmt.Fprintf(b, "type %s string\n\n", e.name)

	b.WriteString("const (\n")
	for _, v := range e.values {
		fmt.Fprintf(b, "%s%s %s = %q\n", e.name, capitalizeFirst(v), e.name, v)
	}
	b.WriteString(")\n\n")
}

func renderStruct(b *strings.Builder, s *structDef) {
	if s.comment != "" {
		fmt.Fprintf(b, "// %s\n", s.comment)
	}

	switch {
	case s.alias != "":
		fmt.Fprintf(b, "type %s = %s\n\n", s.name, s.alias)
	case len(s.fields) == 0:
		fmt.Fprintf(b, "type %s struct{}\n\n", s.name)
	default:
		fmt.Fprintf(b, "type %s struct {\n", s.name)
		for _, f := range s.fields {
			renderField(b, f)
		}
		b.WriteString("}\n\n")
	}

	// An alias names an existing type, which may well be one declared in
	// another package or a slice — neither is a legal method receiver, so a
	// method here would not compile.
	if s.errorBody != "" && s.alias == "" {
		fmt.Fprintf(b, "// Error reports the response payload, so this type satisfies error.\n")
		fmt.Fprintf(b, "func (r %s) Error() string {\n%s\n}\n\n", s.name, s.errorBody)
	}
}

func renderField(b *strings.Builder, f fieldDef) {
	switch {
	case f.embedded:
		fmt.Fprintf(b, "%s\n", f.typ)
	case f.jsonTag == "":
		fmt.Fprintf(b, "%s %s\n", f.name, f.typ)
	default:
		fmt.Fprintf(b, "%s %s `json:%q`\n", f.name, f.typ, f.jsonTag)
	}
}
