// Code generated by openapi2go. DO NOT EDIT.

package generated

type HuntingSkill string

const (
	HuntingSkillLazy       HuntingSkill = "lazy"
	HuntingSkillClueless   HuntingSkill = "clueless"
	HuntingSkillAggressive HuntingSkill = "aggressive"
)

// PolymorphicPet is generated from components.schemas.PolymorphicPet.
type PolymorphicPet struct {
	Name    string `json:"name"`
	PetType string `json:"pet_type"`
}

// PolymorphicCat is generated from components.schemas.PolymorphicCat.
type PolymorphicCat struct {
	PolymorphicPet
	HuntingSkill HuntingSkill `json:"hunting_skill"`
}
