// Code generated by openapi2go. DO NOT EDIT.

package generated

import (
	"context"
	"net/http"
	"net/url"
)

// ListItems is generated for operationId ListItems.
// It performs a get request against paths["/items"] of the OpenAPI spec.
func (c *Client) ListItems(ctx context.Context, params ListItemsParams, opts ...RequestOption) (*ListItemsResponse200, error) {
	const op = "ListItems"

	query := url.Values{}
	if params.Page != nil {
		query.Set("page", formatValue(*params.Page))
	}
	query.Set("pageSize", formatValue(params.PageSize))

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodGet,
		path:   "/items",
		query:  query,
	}, opts)
	if err != nil {
		return nil, err
	}

	if err := resp.expectSuccess(op); err != nil {
		return nil, err
	}

	return decodeJSON[ListItemsResponse200](resp, op)
}

// CreateItem is generated for operationId CreateItem.
// It performs a post request against paths["/items"] of the OpenAPI spec.
// The spec documents error responses 400, 401 with no content; return an *APIError.
func (c *Client) CreateItem(ctx context.Context, req CreateItemRequest, opts ...RequestOption) (*CreateItemResponse201, error) {
	const op = "CreateItem"

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodPost,
		path:   "/items",
		body:   req,
	}, opts)
	if err != nil {
		return nil, err
	}

	if err := resp.expectSuccess(op); err != nil {
		return nil, err
	}

	return decodeJSON[CreateItemResponse201](resp, op)
}

// GetItem is generated for operationId GetItem.
// It performs a get request against paths["/items/{itemId}"] of the OpenAPI spec.
// The spec documents error response 404 with no content; returns an *APIError.
func (c *Client) GetItem(ctx context.Context, params GetItemParams, opts ...RequestOption) (*Item, error) {
	const op = "GetItem"

	header := http.Header{}
	header.Set("X-Api-Key", formatValue(params.XApiKey))
	if params.XRequestId != nil {
		header.Set("X-Request-Id", formatValue(*params.XRequestId))
	}

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodGet,
		path:   "/items/" + pathParam(params.ItemId),
		header: header,
	}, opts)
	if err != nil {
		return nil, err
	}

	if resp.StatusCode == http.StatusBadRequest {
		return nil, decodeError[ValidationError](resp, op)
	}

	if err := resp.expectSuccess(op); err != nil {
		return nil, err
	}

	return decodeJSON[Item](resp, op)
}

// ReplaceItem is generated for operationId ReplaceItem.
// It performs a put request against paths["/items/{itemId}"] of the OpenAPI spec.
func (c *Client) ReplaceItem(ctx context.Context, params ReplaceItemParams, req ReplaceItemRequest, opts ...RequestOption) (*ReplaceItemResponse200, error) {
	const op = "ReplaceItem"

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodPut,
		path:   "/items/" + pathParam(params.ItemId),
		body:   req,
	}, opts)
	if err != nil {
		return nil, err
	}

	if resp.StatusCode == http.StatusConflict {
		return nil, decodeError[ConflictError](resp, op)
	}

	if err := resp.expectSuccess(op); err != nil {
		return nil, err
	}

	return decodeJSON[ReplaceItemResponse200](resp, op)
}

// DeleteItem is generated for operationId DeleteItem.
// It performs a delete request against paths["/items/{itemId}"] of the OpenAPI spec.
func (c *Client) DeleteItem(ctx context.Context, params DeleteItemParams, opts ...RequestOption) error {
	const op = "DeleteItem"

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodDelete,
		path:   "/items/" + pathParam(params.ItemId),
	}, opts)
	if err != nil {
		return err
	}

	if resp.StatusCode == http.StatusNotFound {
		return decodeError[NotFoundError](resp, op)
	}

	return resp.expectSuccess(op)
}

// ArchiveItem is generated for operationId ArchiveItem.
// It performs a patch request against paths["/items/{itemId}/archive"] of the OpenAPI spec.
func (c *Client) ArchiveItem(ctx context.Context, params ArchiveItemParams, opts ...RequestOption) error {
	const op = "ArchiveItem"

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodPatch,
		path:   "/items/" + pathParam(params.ItemId) + "/archive",
	}, opts)
	if err != nil {
		return err
	}

	return resp.expectSuccess(op)
}
