// Code generated by openapi2go. DO NOT EDIT.

package generated

import (
	"bytes"
	"context"
	"encoding"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// maxResponseBytes caps how much of a response body the client buffers, so a
// server that streams without end cannot make a generated call consume
// unbounded memory.
const maxResponseBytes = 32 << 20

// drainLimit caps how much of an unread response body is discarded before
// closing it. Reading a body to EOF is what lets net/http return the
// connection to its idle pool, so a call that ignores the body still drains
// it — bounded, so a hostile server cannot make Close block forever.
const drainLimit = 64 << 10

// bodySummaryLimit caps how much of an undecodable body an APIError repeats.
const bodySummaryLimit = 256

// minSuccessStatus and maxSuccessStatus bound the status codes a generated
// operation treats as success.
const (
	minSuccessStatus = 200
	maxSuccessStatus = 299
)

// ErrResponseTooLarge reports a response body past the client's size cap.
var ErrResponseTooLarge = errors.New("response body too large")

// ErrDecode reports a response body that was not the shape the OpenAPI
// document declared for its status code.
var ErrDecode = errors.New("decoding response body")

// RequestOption adjusts an outgoing request just before it is sent.
// Returning an error aborts the call without sending anything, so an option
// that has to mint a credential can report failure rather than silently
// sending an unauthenticated request.
type RequestOption func(*http.Request) error

// WithHeader returns a RequestOption that sets one request header.
func WithHeader(key, value string) RequestOption {
	return func(r *http.Request) error {
		r.Header.Set(key, value)

		return nil
	}
}

// WithBearerToken returns a RequestOption that sets an RFC 6750 bearer
// Authorization header.
func WithBearerToken(token string) RequestOption {
	return WithHeader("Authorization", "Bearer "+token)
}

// Client calls the operations of the OpenAPI document this package was
// generated from. Its zero value is not usable; construct one with NewClient.
type Client struct {
	baseURL string
	http    *http.Client
	opts    []RequestOption
}

// NewClient returns a Client that sends every request to baseURL using
// httpClient, applying opts to each request ahead of any per-call option. A
// nil httpClient selects http.DefaultClient.
func NewClient(baseURL string, httpClient *http.Client, opts ...RequestOption) *Client {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	return &Client{baseURL: baseURL, http: httpClient, opts: opts}
}

// request is one generated operation call, assembled by the generated method
// and executed by do. It is unexported so the generated package's API surface
// stays the operation methods themselves.
type request struct {
	op      string      // operationId, for error messages
	method  string      // HTTP method
	path    string      // request path, already escaped, beginning with "/"
	query   url.Values  // nil when the operation declares no query parameters
	header  http.Header // nil when the operation sets no headers
	cookies []*http.Cookie
	body    any // nil when the operation has no request body
}

// HTTPResponse is a completed exchange whose body has already been read and
// whose connection has been released, so its fields stay valid for as long as
// the caller holds them.
//
// It is named HTTPResponse rather than Response because it shares a namespace
// with every generated schema type, and "Response" is a plausible schema name.
type HTTPResponse struct {
	StatusCode int
	Status     string
	Header     http.Header
	Body       []byte

	// method and requestURL describe the request that produced this
	// response; their only job is to fill in an APIError.
	method     string
	requestURL string
}

// do sends r and returns the completed exchange. A non-nil error means the
// request never produced a response, or its body could not be read; a
// response with any status at all, 5xx included, comes back as a non-nil
// HTTPResponse and a nil error, leaving the generated method to decide which
// statuses are failures.
func (c *Client) do(ctx context.Context, r request, opts []RequestOption) (*HTTPResponse, error) {
	httpReq, err := c.buildRequest(ctx, r, opts)
	if err != nil {
		return nil, err
	}

	// bodyclose cannot see through readBody's deferred Close, which runs on
	// every path including its own error returns.
	httpResp, err := c.http.Do(httpReq) //nolint:bodyclose // readBody closes it
	if err != nil {
		return nil, fmt.Errorf("%s: %w", r.op, err)
	}

	respBody, err := readBody(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", r.op, err)
	}

	return &HTTPResponse{
		StatusCode: httpResp.StatusCode,
		Status:     httpResp.Status,
		Header:     httpResp.Header,
		Body:       respBody,
		method:     httpReq.Method,
		requestURL: httpReq.URL.String(),
	}, nil
}

// buildRequest assembles the outgoing request for r: JSON body, URL, the
// default Accept/Content-Type headers, then the operation's own parameters
// and finally the request options, each layer overriding the one before it.
func (c *Client) buildRequest(ctx context.Context, r request, opts []RequestOption) (*http.Request, error) {
	var body io.Reader

	if r.body != nil {
		encoded, err := json.Marshal(r.body)
		if err != nil {
			return nil, fmt.Errorf("%s: encoding request body: %w", r.op, err)
		}

		body = bytes.NewReader(encoded)
	}

	reqURL, err := resolveURL(c.baseURL, r.path, r.query)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", r.op, err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, r.method, reqURL, body)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", r.op, err)
	}

	httpReq.Header.Set("Accept", "application/json")

	if r.body != nil {
		httpReq.Header.Set("Content-Type", "application/json")
	}

	for name, values := range r.header {
		for _, v := range values {
			httpReq.Header.Add(name, v)
		}
	}

	for _, cookie := range r.cookies {
		httpReq.AddCookie(cookie)
	}

	if err := applyOptions(httpReq, r.op, c.opts, opts); err != nil {
		return nil, err
	}

	return httpReq, nil
}

// resolveURL joins base and an already-escaped path, then appends query.
// url.JoinPath collapses a trailing slash on base, keeps any base path
// prefix, and — unlike assigning to URL.Path — does not re-escape a segment
// that pathParam already escaped.
func resolveURL(base, path string, query url.Values) (string, error) {
	joined, err := url.JoinPath(base, path)
	if err != nil {
		return "", fmt.Errorf("building URL: %w", err)
	}

	if len(query) > 0 {
		joined += "?" + query.Encode()
	}

	return joined, nil
}

// applyOptions runs each group of options against req in order, stopping at
// the first failure. Taking the groups rather than one concatenated slice
// keeps do from allocating a merged slice per request, and from the aliasing
// bug an append onto c.opts would introduce.
func applyOptions(req *http.Request, op string, groups ...[]RequestOption) error {
	for _, group := range groups {
		for _, apply := range group {
			if err := apply(req); err != nil {
				return fmt.Errorf("%s: applying request option: %w", op, err)
			}
		}
	}

	return nil
}

// readBody buffers up to maxResponseBytes of rc, then always drains and
// closes it so net/http can reuse the connection even for an operation whose
// body the caller never looks at.
func readBody(rc io.ReadCloser) ([]byte, error) {
	defer func() {
		_, _ = io.CopyN(io.Discard, rc, drainLimit)
		_ = rc.Close()
	}()

	// The extra byte is what distinguishes "exactly at the cap" from
	// "truncated".
	body, err := io.ReadAll(io.LimitReader(rc, maxResponseBytes+1))
	if err != nil {
		return nil, fmt.Errorf("reading response body: %w", err)
	}

	if len(body) > maxResponseBytes {
		return nil, fmt.Errorf("%w: over %d bytes", ErrResponseTooLarge, maxResponseBytes)
	}

	return body, nil
}

// APIError is the error a generated operation returns for any response it
// does not treat as success. It always carries the whole exchange, so a
// status the OpenAPI document never described stays diagnosable; when the
// status did match a documented error schema, the decoded payload is
// reachable through errors.As.
type APIError struct {
	Op         string
	Method     string
	URL        string
	StatusCode int
	Status     string
	Header     http.Header
	Body       []byte

	payload error
}

// Error reports the operation, request, and status, plus the documented
// payload's own message when one decoded, or a bounded excerpt of the body
// when none did.
func (e *APIError) Error() string {
	msg := fmt.Sprintf("%s: %s %s: %s", e.Op, e.Method, e.URL, e.Status)

	if e.payload != nil {
		if detail := e.payload.Error(); detail != "" {
			return msg + ": " + detail
		}
	}

	if summary := summarize(e.Body); summary != "" {
		return msg + ": " + summary
	}

	return msg
}

// Unwrap returns the decoded payload of a documented error response, so
// errors.As recovers the generated error type, or nil when the response had
// no schema or its body did not match one.
func (e *APIError) Unwrap() error { return e.payload }

// summarize renders body as a single bounded line for an error message.
func summarize(body []byte) string {
	text := strings.Join(strings.Fields(string(body)), " ")
	if len(text) > bodySummaryLimit {
		return text[:bodySummaryLimit] + "..."
	}

	return text
}

// apiError builds the envelope describing r, with no decoded payload.
func (r *HTTPResponse) apiError(op string) *APIError {
	return &APIError{
		Op:         op,
		Method:     r.method,
		URL:        r.requestURL,
		StatusCode: r.StatusCode,
		Status:     r.Status,
		Header:     r.Header,
		Body:       r.Body,
	}
}

// expectSuccess returns an APIError for any status outside 2xx. Generated
// methods call it after their documented error cases, so a status the
// document never mentioned fails loudly instead of being decoded into the
// success type.
//
// A 3xx counts as a failure: http.Client follows redirects, so one arriving
// here is an unfollowed redirect rather than a result.
func (r *HTTPResponse) expectSuccess(op string) error {
	if r.StatusCode >= minSuccessStatus && r.StatusCode <= maxSuccessStatus {
		return nil
	}

	return r.apiError(op)
}

// expectSuccessDefault is expectSuccess for an operation whose spec declares
// a "default" response: any status outside 2xx that no explicit case claimed
// is the default response, so its schema T is decoded into the APIError
// rather than the envelope being returned bare.
func expectSuccessDefault[T error](r *HTTPResponse, op string) error {
	if r.StatusCode >= minSuccessStatus && r.StatusCode <= maxSuccessStatus {
		return nil
	}

	return decodeError[T](r, op)
}

// decodeError builds the APIError for a response whose status matched a
// documented error schema T. T is the generated error type itself rather than
// a pointer to it, so the payload a caller recovers with errors.As is a T
// value — matching the value receiver the generator gives every Error method.
//
// A body that does not decode is not itself reported: the status is already
// the failure, and replacing it with a JSON syntax error would lose that.
func decodeError[T error](r *HTTPResponse, op string) error {
	e := r.apiError(op)

	if len(bytes.TrimSpace(r.Body)) == 0 {
		return e
	}

	var payload T
	if err := json.Unmarshal(r.Body, &payload); err != nil {
		return e
	}

	e.payload = payload

	return e
}

// decodeJSON decodes r's body into a new T. An empty body — a 204, or any
// response a server sent without content — yields the zero value rather than
// the "unexpected end of JSON input" json.Unmarshal reports for it.
func decodeJSON[T any](r *HTTPResponse, op string) (*T, error) {
	var v T

	if len(bytes.TrimSpace(r.Body)) == 0 {
		return &v, nil
	}

	if err := json.Unmarshal(r.Body, &v); err != nil {
		return nil, fmt.Errorf("%s: %w for status %d: %w", op, ErrDecode, r.StatusCode, err)
	}

	return &v, nil
}

// pathParam renders v as a single escaped path segment.
func pathParam(v any) string {
	s := url.PathEscape(formatValue(v))

	// PathEscape leaves "." and ".." alone, and url.JoinPath would then
	// resolve them away, retargeting the request at a parent collection.
	switch s {
	case ".":
		return "%2E"
	case "..":
		return "%2E%2E"
	}

	return s
}

// formatValue renders v as the text of a path, query, or header parameter.
// It replaces the fmt.Sprint the generator used to emit, which rendered a
// float64 1000000 as "1e+06" and a time.Time in Go's default layout rather
// than RFC 3339. Every remaining kind — all integer widths, bool, and any
// fmt.Stringer — fmt.Sprint already renders correctly, so it stays the
// fallback rather than being reimplemented.
func formatValue(v any) string {
	switch v := v.(type) {
	case nil:
		return ""
	case string:
		return v
	case []byte:
		return string(v)
	case float32:
		return strconv.FormatFloat(float64(v), 'f', -1, 32)
	case float64:
		return strconv.FormatFloat(v, 'f', -1, 64)
	case encoding.TextMarshaler:
		if text, err := v.MarshalText(); err == nil {
			return string(text)
		}
	}

	return fmt.Sprint(v)
}
