// Code generated by openapi2go. DO NOT EDIT.

package generated

type HuntingSkill string

const (
	HuntingSkillLazy       HuntingSkill = "lazy"
	HuntingSkillClueless   HuntingSkill = "clueless"
	HuntingSkillAggressive HuntingSkill = "aggressive"
)

// SimpleUser is generated from components.schemas.SimpleUser.
type SimpleUser struct {
	Username string `json:"username"`
}

// ArraysAndCollections is generated from components.schemas.ArraysAndCollections.
type ArraysAndCollections struct {
	IntegerList []int64      `json:"integer_list,omitempty"`
	ObjectList  []SimpleUser `json:"object_list,omitempty"`
	StringList  []string     `json:"string_list,omitempty"`
}

// BaseModel is generated from components.schemas.BaseModel.
type BaseModel struct {
	CreatedAt DateTime `json:"created_at,omitzero"`
	Id        string   `json:"id"`
}

// Bicycle is generated from components.schemas.Bicycle.
type Bicycle struct {
	FrameSize   string `json:"frame_size,omitempty"`
	HasBasket   bool   `json:"has_basket"`
	VehicleType string `json:"vehicle_type"`
}

// Car is generated from components.schemas.Car.
type Car struct {
	LicensePlate    string `json:"license_plate"`
	SeatingCapacity int32  `json:"seating_capacity,omitempty"`
	VehicleType     string `json:"vehicle_type"`
}

// CompositionAllOf is generated from components.schemas.CompositionAllOf.
type CompositionAllOf struct {
	BaseModel
	ExtendedProperty string `json:"extended_property"`
}

// MapsAndDictionaries is generated from components.schemas.MapsAndDictionaries.
type MapsAndDictionaries struct {
	ObjectMap map[string]SimpleUser `json:"object_map,omitempty"`
	StringMap map[string]string     `json:"string_map,omitempty"`
}

// NullableFields is generated from components.schemas.NullableFields.
type NullableFields struct {
	NonNullableString string  `json:"non_nullable_string,omitempty"`
	NullableInt       *int64  `json:"nullable_int,omitempty"`
	NullableString    *string `json:"nullable_string,omitempty"`
}

// OneOfObjectsWithoutDiscriminator is generated from components.schemas.OneOfObjectsWithoutDiscriminator.
type OneOfObjectsWithoutDiscriminator struct {
	AssignedTo OneOf[string, SimpleUser] `json:"assigned_to,omitzero"`
}

// OneOfPrimitives is generated from components.schemas.OneOfPrimitives.
type OneOfPrimitives struct {
	IdOrCode OneOf[string, int64] `json:"id_or_code,omitzero"`
}

// PolymorphicPet is generated from components.schemas.PolymorphicPet.
type PolymorphicPet struct {
	Name    string `json:"name"`
	PetType string `json:"pet_type"`
}

// PolymorphicCat is generated from components.schemas.PolymorphicCat.
type PolymorphicCat struct {
	PolymorphicPet
	HuntingSkill HuntingSkill `json:"hunting_skill"`
}

// PrimitivesAndFormats is generated from components.schemas.PrimitivesAndFormats.
type PrimitivesAndFormats struct {
	BinaryField   string   `json:"binary_field,omitempty"`
	BooleanField  bool     `json:"boolean_field,omitempty"`
	ByteField     []byte   `json:"byte_field,omitempty"`
	DateField     Date     `json:"date_field,omitzero"`
	DateTimeField DateTime `json:"date_time_field,omitzero"`
	DoubleField   float64  `json:"double_field,omitempty"`
	FloatField    float32  `json:"float_field,omitempty"`
	Int32Field    int32    `json:"int32_field,omitempty"`
	Int64Field    int64    `json:"int64_field,omitempty"`
	PasswordField string   `json:"password_field,omitempty"`
	StringField   string   `json:"string_field,omitempty"`
}

// ReadWriteOnly is generated from components.schemas.ReadWriteOnly.
type ReadWriteOnly struct {
	Id          string `json:"id,omitempty"`
	NormalField string `json:"normal_field,omitempty"`
	Password    string `json:"password,omitempty"`
}

// RequiredAndOptional is generated from components.schemas.RequiredAndOptional.
type RequiredAndOptional struct {
	OptionalInteger int32  `json:"optional_integer,omitempty"`
	OptionalString  string `json:"optional_string,omitempty"`
	RequiredInteger int32  `json:"required_integer"`
	RequiredString  string `json:"required_string"`
}

// Vehicle is generated from components.schemas.Vehicle.
type Vehicle = Discriminated[Car, Bicycle]

// VehicleUnion is generated from components.schemas.VehicleUnion.
type VehicleUnion struct {
	BackupVehicles []Vehicle `json:"backup_vehicles,omitempty"`
	MainVehicle    Vehicle   `json:"main_vehicle"`
}
