version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - godot
    - godox
    - gomodguard
    - gosec
    - nlreturn
    - noinlineerr
    - paralleltest
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  exclusions:
    rules:
      - linters:
          - revive
        text: "package-comments: should have a package comment"
      - linters:
          - wsl_v5
        text: "missing whitespace above this line "
formatters:
  enable:
    - goimports
    - gofumpt
  settings:
    goimports:
      local-prefixes:
        - github.com/artem-kuznetsov-intellectsoft/playground
    gofumpt:
      extra-rules: true
issues:
  new: true
