// Code generated by openapi2go. DO NOT EDIT.

package generated

import (
	"context"
	"net/http"
)

// CustomerControllerCreateCustomer is generated for operationId CustomerController_createCustomer.
// It performs a post request against paths["/customer"] of the OpenAPI spec.
// The spec documents error responses 400, 401 with no content; return an *APIError.
func (c *Client) CustomerControllerCreateCustomer(ctx context.Context, req CustomerControllerCreateCustomerRequest, opts ...RequestOption) (*CustomerControllerCreateCustomerResponse201, error) {
	const op = "CustomerControllerCreateCustomer"

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodPost,
		path:   "/customer",
		body:   req,
	}, opts)
	if err != nil {
		return nil, err
	}

	if err := resp.expectSuccess(op); err != nil {
		return nil, err
	}

	return decodeJSON[CustomerControllerCreateCustomerResponse201](resp, op)
}
