// Code generated by openapi2go. DO NOT EDIT.

package generated

import (
	"context"
	"net/http"
)

// ListReports is generated for operationId ListReports.
// It performs a get request against paths["/reports"] of the OpenAPI spec.
func (c *Client) ListReports(ctx context.Context, opts ...RequestOption) (*ListReportsResponse200, error) {
	const op = "ListReports"

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodGet,
		path:   "/reports",
	}, opts)
	if err != nil {
		return nil, err
	}

	switch resp.StatusCode {
	case http.StatusInternalServerError:
		return nil, decodeError[ServerError](resp, op)
	case http.StatusServiceUnavailable:
		return nil, decodeError[ServerError](resp, op)
	}

	if err := resp.expectSuccess(op); err != nil {
		return nil, err
	}

	return decodeJSON[ListReportsResponse200](resp, op)
}

// CreateReport is generated for operationId CreateReport.
// It performs a post request against paths["/reports"] of the OpenAPI spec.
func (c *Client) CreateReport(ctx context.Context, req CreateReportRequest, opts ...RequestOption) (*Report, error) {
	const op = "CreateReport"

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodPost,
		path:   "/reports",
		body:   req,
	}, opts)
	if err != nil {
		return nil, err
	}

	if err := expectSuccessDefault[ServerError](resp, op); err != nil {
		return nil, err
	}

	return decodeJSON[Report](resp, op)
}

// DeleteReport is generated for operationId DeleteReport.
// It performs a delete request against paths["/reports/{reportId}"] of the OpenAPI spec.
func (c *Client) DeleteReport(ctx context.Context, params DeleteReportParams, opts ...RequestOption) (*Report, error) {
	const op = "DeleteReport"

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodDelete,
		path:   "/reports/" + pathParam(params.ReportId),
	}, opts)
	if err != nil {
		return nil, err
	}

	if err := resp.expectSuccess(op); err != nil {
		return nil, err
	}

	return decodeJSON[Report](resp, op)
}
