// Code generated by openapi2go. DO NOT EDIT.

package generated

// Report is generated from components.schemas.Report.
type Report struct {
	Id    string `json:"id,omitempty"`
	Title string `json:"title,omitempty"`
}

type ListReportsResponse200 struct {
	Reports []Report `json:"reports,omitempty"`
}

// ServerError is generated from components.schemas.ServerError.
type ServerError struct {
	Code    int64  `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}

// Error reports the response payload, so this type satisfies error.
func (r ServerError) Error() string {
	if r.Message != "" {
		return r.Message
	}

	return "ServerError"
}

type CreateReportRequest struct {
	Report
}

// DeleteReportParams is generated for operationId DeleteReport.
type DeleteReportParams struct {
	ReportId string
}
