// Code generated by openapi2go. DO NOT EDIT.

package generated

// Capacity represents the whether the company acts for its own account or with third-party funds.
type Capacity string

const (
	CapacityOWN_ACCOUNT       Capacity = "OWN_ACCOUNT"
	CapacityTHIRD_PARTY_FUNDS Capacity = "THIRD_PARTY_FUNDS"
)

// CrsClassification represents the common Reporting Standard classification.
type CrsClassification string

const (
	CrsClassificationACTIVE_NFE            CrsClassification = "ACTIVE_NFE"
	CrsClassificationPASSIVE_NFE           CrsClassification = "PASSIVE_NFE"
	CrsClassificationFINANCIAL_INSTITUTION CrsClassification = "FINANCIAL_INSTITUTION"
)

// LegalForm represents the legal form; OTHER uses legalFormOther.
type LegalForm string

const (
	LegalFormLISTED_PUBLIC_COMPANY           LegalForm = "LISTED_PUBLIC_COMPANY"
	LegalFormREGULATED_FINANCIAL_INSTITUTION LegalForm = "REGULATED_FINANCIAL_INSTITUTION"
	LegalFormREGULATED_INVESTMENT_FUND       LegalForm = "REGULATED_INVESTMENT_FUND"
	LegalFormPRIVATE_LIMITED_COMPANY         LegalForm = "PRIVATE_LIMITED_COMPANY"
	LegalFormPUBLIC_LIMITED_COMPANY          LegalForm = "PUBLIC_LIMITED_COMPANY"
	LegalFormCOOPERATIVE_MUTUAL_ENTITY       LegalForm = "COOPERATIVE_MUTUAL_ENTITY"
	LegalFormPARTNERSHIP_CIVIL_COMPANY       LegalForm = "PARTNERSHIP_CIVIL_COMPANY"
	LegalFormFOREIGN_BRANCH                  LegalForm = "FOREIGN_BRANCH"
	LegalFormHOLDING_SPV                     LegalForm = "HOLDING_SPV"
	LegalFormTRUST_OR_SIMILAR_ARRANGEMENT    LegalForm = "TRUST_OR_SIMILAR_ARRANGEMENT"
	LegalFormFOUNDATION_OR_ENDOWMENT         LegalForm = "FOUNDATION_OR_ENDOWMENT"
	LegalFormNON_PROFIT_ASSOCIATION_NGO      LegalForm = "NON_PROFIT_ASSOCIATION_NGO"
	LegalFormGOVERNMENT_PUBLIC_AUTHORITY     LegalForm = "GOVERNMENT_PUBLIC_AUTHORITY"
	LegalFormSTATE_OWNED_ENTERPRISE          LegalForm = "STATE_OWNED_ENTERPRISE"
	LegalFormOTHER                           LegalForm = "OTHER"
	LegalFormSOLE_PROPRIETORSHIP             LegalForm = "SOLE_PROPRIETORSHIP"
)

// PreferredWalletChain represents the preferred wallet network for incoming settlements.
type PreferredWalletChain string

const (
	PreferredWalletChainRIPPLE    PreferredWalletChain = "RIPPLE"
	PreferredWalletChainETHEREUM  PreferredWalletChain = "ETHEREUM"
	PreferredWalletChainPOLYGON   PreferredWalletChain = "POLYGON"
	PreferredWalletChainAVALANCHE PreferredWalletChain = "AVALANCHE"
	PreferredWalletChainPLASMA    PreferredWalletChain = "PLASMA"
	PreferredWalletChainSOLANA    PreferredWalletChain = "SOLANA"
	PreferredWalletChainP_LAYER   PreferredWalletChain = "P_LAYER"
)

// Sector represents the business sector; OTHER uses sectorOther.
type Sector string

const (
	SectorAGRICULTURE_FORESTRY_FISHING            Sector = "AGRICULTURE_FORESTRY_FISHING"
	SectorMINING_QUARRYING_EXTRACTIVES            Sector = "MINING_QUARRYING_EXTRACTIVES"
	SectorMANUFACTURING_GENERAL                   Sector = "MANUFACTURING_GENERAL"
	SectorTEXTILES_CLOTHING_LEATHER_MANUFACTURING Sector = "TEXTILES_CLOTHING_LEATHER_MANUFACTURING"
	SectorENERGY_UTILITIES                        Sector = "ENERGY_UTILITIES"
	SectorCONSTRUCTION_PUBLIC_WORKS               Sector = "CONSTRUCTION_PUBLIC_WORKS"
	SectorWHOLESALE_RETAIL_GENERAL                Sector = "WHOLESALE_RETAIL_GENERAL"
	SectorPRECIOUS_METALS_JEWELLERY_ART_ANTIQUES  Sector = "PRECIOUS_METALS_JEWELLERY_ART_ANTIQUES"
	SectorMOTOR_VEHICLE_BOAT_LUXURY_GOODS         Sector = "MOTOR_VEHICLE_BOAT_LUXURY_GOODS"
	SectorTRANSPORT_LOGISTICS                     Sector = "TRANSPORT_LOGISTICS"
	SectorPOSTAL_COURIER_VALUE_TRANSFER           Sector = "POSTAL_COURIER_VALUE_TRANSFER"
	SectorACCOMMODATION_FOOD_SERVICE              Sector = "ACCOMMODATION_FOOD_SERVICE"
	SectorINFORMATION_IT_COMMUNICATION            Sector = "INFORMATION_IT_COMMUNICATION"
	SectorFINANCIAL_INSURANCE_SERVICES            Sector = "FINANCIAL_INSURANCE_SERVICES"
	SectorMONEY_SERVICES_CURRENCY_EXCHANGE        Sector = "MONEY_SERVICES_CURRENCY_EXCHANGE"
	SectorCRYPTO_ASSET_SERVICES                   Sector = "CRYPTO_ASSET_SERVICES"
	SectorREAL_ESTATE                             Sector = "REAL_ESTATE"
	SectorLEGAL_ACCOUNTING_AUDIT_ADVISORY         Sector = "LEGAL_ACCOUNTING_AUDIT_ADVISORY"
	SectorOTHER_PROFESSIONAL_SCIENTIFIC_TECHNICAL Sector = "OTHER_PROFESSIONAL_SCIENTIFIC_TECHNICAL"
	SectorADMINISTRATIVE_SUPPORT_SERVICES         Sector = "ADMINISTRATIVE_SUPPORT_SERVICES"
	SectorGAMBLING_BETTING_CASINOS                Sector = "GAMBLING_BETTING_CASINOS"
	SectorARTS_ENTERTAINMENT_RECREATION_OTHER     Sector = "ARTS_ENTERTAINMENT_RECREATION_OTHER"
	SectorARMS_DEFENCE_DUAL_USE_GOODS             Sector = "ARMS_DEFENCE_DUAL_USE_GOODS"
	SectorPUBLIC_ADMIN_EDUCATION_HEALTH_SOCIAL    Sector = "PUBLIC_ADMIN_EDUCATION_HEALTH_SOCIAL"
	SectorPERSONAL_HOUSEHOLD_SERVICES             Sector = "PERSONAL_HOUSEHOLD_SERVICES"
	SectorOTHER                                   Sector = "OTHER"
)

// ExpectedYearlyTxCount represents the expected yearly transaction count. Allowed values: LT_50 = < 50 transactions / year; B_50_500 = 50 - 500 transactions / year; B_500_5000 = 500 - 5,000 transactions / year; B_5000_50000 = 5,000 - 50,000 transactions / year; GT_50000 = > 50,000 transactions / year.
type ExpectedYearlyTxCount string

const (
	ExpectedYearlyTxCountLT_50        ExpectedYearlyTxCount = "LT_50"
	ExpectedYearlyTxCountB_50_500     ExpectedYearlyTxCount = "B_50_500"
	ExpectedYearlyTxCountB_500_5000   ExpectedYearlyTxCount = "B_500_5000"
	ExpectedYearlyTxCountB_5000_50000 ExpectedYearlyTxCount = "B_5000_50000"
	ExpectedYearlyTxCountGT_50000     ExpectedYearlyTxCount = "GT_50000"
)

// ExpectedYearlyVolume represents the expected yearly transaction volume. Allowed values: LT_100K = < €100,000; B_100K_1M = €100,000 - €1,000,000; B_1M_10M = €1,000,000 - €10,000,000; B_10M_50M = €10,000,000 - €50,000,000; B_50M_250M = €50,000,000 - €250,000,000; GT_250M = > €250,000,000.
type ExpectedYearlyVolume string

const (
	ExpectedYearlyVolumeLT_100K    ExpectedYearlyVolume = "LT_100K"
	ExpectedYearlyVolumeB_100K_1M  ExpectedYearlyVolume = "B_100K_1M"
	ExpectedYearlyVolumeB_1M_10M   ExpectedYearlyVolume = "B_1M_10M"
	ExpectedYearlyVolumeB_10M_50M  ExpectedYearlyVolume = "B_10M_50M"
	ExpectedYearlyVolumeB_50M_250M ExpectedYearlyVolume = "B_50M_250M"
	ExpectedYearlyVolumeGT_250M    ExpectedYearlyVolume = "GT_250M"
)

// FinancialAssets represents the total financial assets. Allowed values: LT_100K = < €100,000; B_100K_1M = €100,000 - €1,000,000; B_1M_10M = €1,000,000 - €10,000,000; B_10M_100M = €10,000,000 - €100,000,000; GT_100M = > €100,000,000; OTHER = Other.
type FinancialAssets string

const (
	FinancialAssetsLT_100K    FinancialAssets = "LT_100K"
	FinancialAssetsB_100K_1M  FinancialAssets = "B_100K_1M"
	FinancialAssetsB_1M_10M   FinancialAssets = "B_1M_10M"
	FinancialAssetsB_10M_100M FinancialAssets = "B_10M_100M"
	FinancialAssetsGT_100M    FinancialAssets = "GT_100M"
	FinancialAssetsOTHER      FinancialAssets = "OTHER"
)

type ProductsSubscribed string

const (
	ProductsSubscribedDIRECT_MINT_BURN ProductsSubscribed = "DIRECT_MINT_BURN"
	ProductsSubscribedEUR_ACCOUNT      ProductsSubscribed = "EUR_ACCOUNT"
	ProductsSubscribedFX_SWAP          ProductsSubscribed = "FX_SWAP"
)

// Purpose represents the purpose of the relationship. Allowed values: OPERATIONAL_ACCOUNT = Operational account; SALARY = Salary; INVESTMENT = Investment; TREASURY_MANAGEMENT = Treasury management; ON_OFF_RAMP = On/Off-ramp (fiat <-> crypto); INTERNATIONAL_PAYMENTS = International payments / remittance; OTHER = Other (not listed - please specify).
type Purpose string

const (
	PurposeOPERATIONAL_ACCOUNT    Purpose = "OPERATIONAL_ACCOUNT"
	PurposeSALARY                 Purpose = "SALARY"
	PurposeINVESTMENT             Purpose = "INVESTMENT"
	PurposeTREASURY_MANAGEMENT    Purpose = "TREASURY_MANAGEMENT"
	PurposeON_OFF_RAMP            Purpose = "ON_OFF_RAMP"
	PurposeINTERNATIONAL_PAYMENTS Purpose = "INTERNATIONAL_PAYMENTS"
	PurposeOTHER                  Purpose = "OTHER"
)

// SourceOfFunds represents the source of funds. Allowed values: BUSINESS_TRADING_REVENUE = Business / trading revenue; SHAREHOLDER_CAPITAL_EQUITY_CONTRIBUTION = Shareholder capital / equity contribution; INTRA_GROUP_FINANCING_PARENT_FUNDING = Intra-group financing / parent funding; BANK_LOAN_CREDIT_FACILITY = Bank loan / credit facility; INVESTOR_FUNDRAISING_PROCEEDS = Investor / fundraising proceeds (VC, PE); SALE_OF_ASSETS_BUSINESS = Sale of assets / business; CRYPTO_ASSET_ACTIVITY_PROCEEDS = Proceeds from crypto-asset activity; THIRD_PARTY_CLIENT_FUNDS = Third-party / client funds (not own funds); OTHER = Other (not listed).
type SourceOfFunds string

const (
	SourceOfFundsBUSINESS_TRADING_REVENUE                SourceOfFunds = "BUSINESS_TRADING_REVENUE"
	SourceOfFundsSHAREHOLDER_CAPITAL_EQUITY_CONTRIBUTION SourceOfFunds = "SHAREHOLDER_CAPITAL_EQUITY_CONTRIBUTION"
	SourceOfFundsINTRA_GROUP_FINANCING_PARENT_FUNDING    SourceOfFunds = "INTRA_GROUP_FINANCING_PARENT_FUNDING"
	SourceOfFundsBANK_LOAN_CREDIT_FACILITY               SourceOfFunds = "BANK_LOAN_CREDIT_FACILITY"
	SourceOfFundsINVESTOR_FUNDRAISING_PROCEEDS           SourceOfFunds = "INVESTOR_FUNDRAISING_PROCEEDS"
	SourceOfFundsSALE_OF_ASSETS_BUSINESS                 SourceOfFunds = "SALE_OF_ASSETS_BUSINESS"
	SourceOfFundsCRYPTO_ASSET_ACTIVITY_PROCEEDS          SourceOfFunds = "CRYPTO_ASSET_ACTIVITY_PROCEEDS"
	SourceOfFundsTHIRD_PARTY_CLIENT_FUNDS                SourceOfFunds = "THIRD_PARTY_CLIENT_FUNDS"
	SourceOfFundsOTHER                                   SourceOfFunds = "OTHER"
)

// TurnoverBracket represents the annual turnover. Allowed values: LT_100K = < €100,000; B_100K_1M = €100,000 - €1,000,000; B_1M_10M = €1,000,000 - €10,000,000; B_10M_50M = €10,000,000 - €50,000,000; B_50M_250M = €50,000,000 - €250,000,000; GT_250M = > €250,000,000; OTHER = Other.
type TurnoverBracket string

const (
	TurnoverBracketLT_100K    TurnoverBracket = "LT_100K"
	TurnoverBracketB_100K_1M  TurnoverBracket = "B_100K_1M"
	TurnoverBracketB_1M_10M   TurnoverBracket = "B_1M_10M"
	TurnoverBracketB_10M_50M  TurnoverBracket = "B_10M_50M"
	TurnoverBracketB_50M_250M TurnoverBracket = "B_50M_250M"
	TurnoverBracketGT_250M    TurnoverBracket = "GT_250M"
	TurnoverBracketOTHER      TurnoverBracket = "OTHER"
)

// Direction represents the sEND = outbound; RECEIVE = inbound; BOTH = inbound and outbound.
type Direction string

const (
	DirectionSEND    Direction = "SEND"
	DirectionRECEIVE Direction = "RECEIVE"
	DirectionBOTH    Direction = "BOTH"
)

type DocumentResponseDto struct{}

type CompanyIndividualResponseDto struct{}

type TcAcceptanceResponseDto struct{}

type CompanyUboResponseDto struct{}

// CompanyDetailResponseDto is generated from components.schemas.CompanyDetailResponseDto.
type CompanyDetailResponseDto struct {
	ActivityDescription     *string                        `json:"activityDescription"`
	BrandName               *string                        `json:"brandName"`
	Capacity                *Capacity                      `json:"capacity"`
	Compliance              *Compliance                    `json:"compliance"`
	CreatedAt               DateTime                       `json:"createdAt"`
	CrsClassification       *CrsClassification             `json:"crsClassification"`
	Documents               []DocumentResponseDto          `json:"documents"`
	Email                   *string                        `json:"email"`
	Id                      string                         `json:"id"`
	JurisdictionCountryCode *string                        `json:"jurisdictionCountryCode"`
	KybVerificationLink     string                         `json:"kybVerificationLink"`
	LegalForm               *LegalForm                     `json:"legalForm"`
	LegalFormOther          *string                        `json:"legalFormOther"`
	LegalRepresentatives    []CompanyIndividualResponseDto `json:"legalRepresentatives"`
	Name                    *string                        `json:"name"`
	Phone                   *string                        `json:"phone"`
	PhysicalAddress         *PhysicalAddress               `json:"physicalAddress,omitempty"`
	PreferredBankAccount    *string                        `json:"preferredBankAccount"`
	PreferredWalletAddress  *string                        `json:"preferredWalletAddress"`
	PreferredWalletChain    *PreferredWalletChain          `json:"preferredWalletChain"`
	RegistrationDate        *Date                          `json:"registrationDate"`
	RegistrationNumber      *string                        `json:"registrationNumber"`
	Sector                  *Sector                        `json:"sector"`
	SectorOther             *string                        `json:"sectorOther"`
	TaxId                   *string                        `json:"taxId"`
	TaxResidenceCountryCode *string                        `json:"taxResidenceCountryCode"`
	TcAcceptances           []TcAcceptanceResponseDto      `json:"tcAcceptances"`
	Tin                     *string                        `json:"tin"`
	Ubos                    []CompanyUboResponseDto        `json:"ubos"`
	UpdatedAt               DateTime                       `json:"updatedAt"`
	Website                 *string                        `json:"website"`
}

type Compliance struct {
	ExpectedYearlyTxCount ExpectedYearlyTxCount  `json:"expectedYearlyTxCount,omitempty"`
	ExpectedYearlyVolume  ExpectedYearlyVolume   `json:"expectedYearlyVolume,omitempty"`
	FinancialAssets       FinancialAssets        `json:"financialAssets,omitempty"`
	FinancialAssetsOther  string                 `json:"financialAssetsOther,omitempty"`
	GeographicScope       []GeographicScopeEntry `json:"geographicScope,omitempty"`
	ProductsSubscribed    []ProductsSubscribed   `json:"productsSubscribed,omitempty"`
	Purpose               Purpose                `json:"purpose,omitempty"`
	PurposeDetails        string                 `json:"purposeDetails,omitempty"`
	SourceOfFunds         SourceOfFunds          `json:"sourceOfFunds,omitempty"`
	SourceOfFundsDetails  string                 `json:"sourceOfFundsDetails,omitempty"`
	TurnoverBracket       TurnoverBracket        `json:"turnoverBracket,omitempty"`
	TurnoverBracketOther  string                 `json:"turnoverBracketOther,omitempty"`
	Website               string                 `json:"website,omitempty"`
}

type PhysicalAddress struct {
	AddressLine1 string `json:"addressLine1"`
	AddressLine2 string `json:"addressLine2,omitempty"`
	City         string `json:"city"`
	CountryCode  string `json:"countryCode"`
	ZipCode      string `json:"zipCode"`
}

type GeographicScopeEntry struct {
	CountryCode string    `json:"countryCode"`
	Direction   Direction `json:"direction"`
}
