// Code generated by openapi2go. DO NOT EDIT.

package generated

import (
	"context"
	"net/http"
)

// BrokenTemplate is generated for operationId BrokenTemplate.
// It performs a get request against paths["/broken{template"] of the OpenAPI spec.
func (c *Client) BrokenTemplate(ctx context.Context, opts ...RequestOption) error {
	const op = "BrokenTemplate"

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodGet,
		path:   "/broken{template",
	}, opts)
	if err != nil {
		return err
	}

	return resp.expectSuccess(op)
}

// PostNoData is generated for operationId PostNoData.
// It performs a post request against paths["/nodata"] of the OpenAPI spec.
func (c *Client) PostNoData(ctx context.Context, opts ...RequestOption) error {
	const op = "PostNoData"

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodPost,
		path:   "/nodata",
	}, opts)
	if err != nil {
		return err
	}

	return resp.expectSuccess(op)
}

// GetResource is generated for operationId GetResource.
// It performs a get request against paths["/resource/{id}"] of the OpenAPI spec.
// The spec documents error response 404 with no content; returns an *APIError.
func (c *Client) GetResource(ctx context.Context, params GetResourceParams, opts ...RequestOption) (*GetResourceResponse200, error) {
	const op = "GetResource"

	header := http.Header{}
	header.Set("X-Api-Key", formatValue(params.XApiKey))
	if params.XTraceId != nil {
		header.Set("X-Trace-Id", formatValue(*params.XTraceId))
	}

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodGet,
		path:   "/resource/" + pathParam(params.Id),
		header: header,
	}, opts)
	if err != nil {
		return nil, err
	}

	if err := resp.expectSuccess(op); err != nil {
		return nil, err
	}

	return decodeJSON[GetResourceResponse200](resp, op)
}

// ReplaceResource is generated for operationId ReplaceResource.
// It performs a put request against paths["/resource/{id}"] of the OpenAPI spec.
func (c *Client) ReplaceResource(ctx context.Context, params ReplaceResourceParams, opts ...RequestOption) error {
	const op = "ReplaceResource"

	header := http.Header{}
	header.Set("X-Api-Key", formatValue(params.XApiKey))

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodPut,
		path:   "/resource/" + pathParam(params.Id),
		header: header,
	}, opts)
	if err != nil {
		return err
	}

	return resp.expectSuccess(op)
}

// DeleteResource is generated for operationId DeleteResource.
// It performs a delete request against paths["/resource/{id}"] of the OpenAPI spec.
// The spec documents error response 404 with no content; returns an *APIError.
func (c *Client) DeleteResource(ctx context.Context, params DeleteResourceParams, opts ...RequestOption) error {
	const op = "DeleteResource"

	header := http.Header{}
	header.Set("X-Api-Key", formatValue(params.XApiKey))

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodDelete,
		path:   "/resource/" + pathParam(params.Id),
		header: header,
	}, opts)
	if err != nil {
		return err
	}

	return resp.expectSuccess(op)
}

// OptionsResource is generated for operationId OptionsResource.
// It performs a options request against paths["/resource/{id}"] of the OpenAPI spec.
func (c *Client) OptionsResource(ctx context.Context, params OptionsResourceParams, opts ...RequestOption) error {
	const op = "OptionsResource"

	header := http.Header{}
	header.Set("X-Api-Key", formatValue(params.XApiKey))

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodOptions,
		path:   "/resource/" + pathParam(params.Id),
		header: header,
	}, opts)
	if err != nil {
		return err
	}

	return resp.expectSuccess(op)
}

// HeadResource is generated for operationId HeadResource.
// It performs a head request against paths["/resource/{id}"] of the OpenAPI spec.
func (c *Client) HeadResource(ctx context.Context, params HeadResourceParams, opts ...RequestOption) error {
	const op = "HeadResource"

	header := http.Header{}
	header.Set("X-Api-Key", formatValue(params.XApiKey))

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodHead,
		path:   "/resource/" + pathParam(params.Id),
		header: header,
	}, opts)
	if err != nil {
		return err
	}

	return resp.expectSuccess(op)
}

// PatchResource is generated for operationId PatchResource.
// It performs a patch request against paths["/resource/{id}"] of the OpenAPI spec.
func (c *Client) PatchResource(ctx context.Context, params PatchResourceParams, opts ...RequestOption) error {
	const op = "PatchResource"

	header := http.Header{}
	header.Set("X-Api-Key", formatValue(params.XApiKey))

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodPatch,
		path:   "/resource/" + pathParam(params.Id),
		header: header,
	}, opts)
	if err != nil {
		return err
	}

	return resp.expectSuccess(op)
}

// TraceResource is generated for operationId TraceResource.
// It performs a trace request against paths["/resource/{id}"] of the OpenAPI spec.
func (c *Client) TraceResource(ctx context.Context, params TraceResourceParams, opts ...RequestOption) error {
	const op = "TraceResource"

	header := http.Header{}
	header.Set("X-Api-Key", formatValue(params.XApiKey))

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodTrace,
		path:   "/resource/" + pathParam(params.Id),
		header: header,
	}, opts)
	if err != nil {
		return err
	}

	return resp.expectSuccess(op)
}
