// Code generated by openapi2go. DO NOT EDIT.

package generated

// BaseModel is generated from components.schemas.BaseModel.
type BaseModel struct {
	CreatedAt DateTime `json:"created_at,omitzero"`
	Id        string   `json:"id"`
}

// CompositionAllOf is generated from components.schemas.CompositionAllOf.
type CompositionAllOf struct {
	BaseModel
	ExtendedProperty string `json:"extended_property"`
}
