// Code generated by openapi2go. DO NOT EDIT.

package generated

import (
	"context"
	"net/http"
)

// GetUser is generated for operationId get-user.
// It performs a get request against paths["/user"] of the OpenAPI spec.
// The spec documents error response 404 with no content; returns an *APIError.
func (c *Client) GetUser(ctx context.Context, req GetUserRequest, opts ...RequestOption) (*ResponseOK, error) {
	const op = "GetUser"

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodGet,
		path:   "/user",
		body:   req,
	}, opts)
	if err != nil {
		return nil, err
	}

	if resp.StatusCode == http.StatusBadRequest {
		return nil, decodeError[ResponseBadRequest](resp, op)
	}

	if err := resp.expectSuccess(op); err != nil {
		return nil, err
	}

	return decodeJSON[ResponseOK](resp, op)
}
