// Code generated by openapi2go. DO NOT EDIT.

package generated

type GetUserRequest struct {
	Request
}

// Request is generated from components.schemas.Request.
type Request struct {
	Age  int64  `json:"age,omitempty"`
	Name string `json:"name,omitempty"`
}

// ResponseBadRequest is generated from components.schemas.ResponseBadRequest.
type ResponseBadRequest struct {
	Message string `json:"message,omitempty"`
}

// Error reports the response payload, so this type satisfies error.
func (r ResponseBadRequest) Error() string {
	if r.Message != "" {
		return r.Message
	}

	return "ResponseBadRequest"
}

// ResponseOK is generated from components.schemas.ResponseOK.
type ResponseOK struct {
	Id string `json:"id,omitempty"`
}
