// Code generated by openapi2go. DO NOT EDIT.

package generated

type GetUserRequest struct {
	Id string `json:"id,omitempty"`
}

type GetUserResponse200 struct {
	Age  int64  `json:"age,omitempty"`
	Name string `json:"name,omitempty"`
}
