// Code generated by openapi2go. DO NOT EDIT.

package generated

import (
	"context"
	"net/http"
	"net/url"
)

// GetUserById is generated for operationId get-user-by-id.
// It performs a get request against paths["/user/{userId}"] of the OpenAPI spec.
func (c *Client) GetUserById(ctx context.Context, params GetUserByIdParams, opts ...RequestOption) (*ResponseOK, error) {
	const op = "GetUserById"

	query := url.Values{}
	if params.MiddleName != nil {
		query.Set("middleName", formatValue(*params.MiddleName))
	}

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodGet,
		path:   "/user/" + pathParam(params.UserId),
		query:  query,
	}, opts)
	if err != nil {
		return nil, err
	}

	if err := resp.expectSuccess(op); err != nil {
		return nil, err
	}

	return decodeJSON[ResponseOK](resp, op)
}
