// Code generated by openapi2go. DO NOT EDIT.

package generated

// GetUserByIdParams is generated for operationId get-user-by-id.
type GetUserByIdParams struct {
	MiddleName *string
	UserId     string
}

// ResponseOK is generated from components.schemas.ResponseOK.
type ResponseOK struct {
	Id string `json:"id,omitempty"`
}
