// Code generated by openapi2go. DO NOT EDIT.

package generated

import (
	"context"
	"net/http"
)

// DocumentControllerRequestUpload is generated for operationId DocumentController_requestUpload.
// It performs a post request against paths["/document/upload-request"] of the OpenAPI spec.
func (c *Client) DocumentControllerRequestUpload(ctx context.Context, req DocumentControllerRequestUploadRequest, opts ...RequestOption) error {
	const op = "DocumentControllerRequestUpload"

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodPost,
		path:   "/document/upload-request",
		body:   req,
	}, opts)
	if err != nil {
		return err
	}

	return resp.expectSuccess(op)
}
