// Code generated by openapi2go. DO NOT EDIT.

package generated

// PolymorphicPet is generated from components.schemas.PolymorphicPet.
type PolymorphicPet struct {
	Name    string `json:"name"`
	PetType string `json:"pet_type"`
}
