// Code generated by openapi2go. DO NOT EDIT.

package generated

import (
	"context"
	"net/http"
	"net/url"
)

// Search is generated for operationId Search.
// It performs a get request against paths["/search/{groupId}"] of the OpenAPI spec.
func (c *Client) Search(ctx context.Context, params SearchParams, opts ...RequestOption) (*SearchResponse200, error) {
	const op = "Search"

	query := url.Values{}
	if params.Day != nil {
		query.Set("day", formatValue(*params.Day))
	}
	if params.Exact != nil {
		query.Set("exact", formatValue(*params.Exact))
	}
	for _, v := range params.Ids {
		query.Add("ids", formatValue(v))
	}
	if params.Score != nil {
		query.Set("score", formatValue(*params.Score))
	}
	if params.Since != nil {
		query.Set("since", formatValue(*params.Since))
	}
	for _, v := range params.Tags {
		query.Add("tags", formatValue(v))
	}

	var cookies []*http.Cookie
	cookies = append(cookies, &http.Cookie{Name: "session", Value: formatValue(params.Session)})

	resp, err := c.do(ctx, request{
		op:      op,
		method:  http.MethodGet,
		path:    "/search/" + pathParam(params.GroupId),
		query:   query,
		cookies: cookies,
	}, opts)
	if err != nil {
		return nil, err
	}

	if err := resp.expectSuccess(op); err != nil {
		return nil, err
	}

	return decodeJSON[SearchResponse200](resp, op)
}
