// Code generated by openapi2go. DO NOT EDIT.

package generated

// SearchParams is generated for operationId Search.
type SearchParams struct {
	Day     *Date
	Exact   *bool
	GroupId string
	Ids     []int64
	Score   *float64
	Session string
	Since   *DateTime
	Tags    []string
}

type SearchResponse200 struct {
	Total int64 `json:"total,omitempty"`
}
