// Code generated by openapi2go. DO NOT EDIT.

package generated

import (
	"context"
	"net/http"
	"net/url"
)

// CustomerControllerGetAllCustomers is generated for operationId CustomerController_getAllCustomers.
// It performs a get request against paths["/customer"] of the OpenAPI spec.
// The spec documents error response 401 with no content; returns an *APIError.
func (c *Client) CustomerControllerGetAllCustomers(ctx context.Context, params CustomerControllerGetAllCustomersParams, opts ...RequestOption) (*CustomerControllerGetAllCustomersResponse200, error) {
	const op = "CustomerControllerGetAllCustomers"

	query := url.Values{}
	query.Set("limit", formatValue(params.Limit))
	if params.Page != nil {
		query.Set("page", formatValue(*params.Page))
	}

	resp, err := c.do(ctx, request{
		op:     op,
		method: http.MethodGet,
		path:   "/customer",
		query:  query,
	}, opts)
	if err != nil {
		return nil, err
	}

	if err := resp.expectSuccess(op); err != nil {
		return nil, err
	}

	return decodeJSON[CustomerControllerGetAllCustomersResponse200](resp, op)
}
