// Code generated by openapi2go. DO NOT EDIT.

package generated

// CustomerControllerGetAllCustomersParams is generated for operationId CustomerController_getAllCustomers.
type CustomerControllerGetAllCustomersParams struct {
	Limit float64
	Page  *float64
}

type CustomerListCompanyResponseDto struct{}

type CustomerListIndividualResponseDto struct{}

type CustomerControllerGetAllCustomersResponse200 struct {
	Customers  []OneOf[CustomerListCompanyResponseDto, CustomerListIndividualResponseDto] `json:"customers,omitempty"`
	Pagination Pagination                                                                 `json:"pagination,omitzero"`
}

type Pagination struct {
	Limit      float64 `json:"limit,omitempty"`
	Page       float64 `json:"page,omitempty"`
	Total      float64 `json:"total,omitempty"`
	TotalPages float64 `json:"totalPages,omitempty"`
}
